language: cpp
os: osx
osx_image: xcode7.2
compiler: clang
install: true
script: make

# Reinstall CocoaPods because the preinstalled CocoaPods crashes with a segmentation fault.
before_install:
  - rvm install ruby-2.2.4
  - rvm --default use 2.2.4
  - gem install cocoapods
  - pod setup
